### ISSUE TITLE
Stafsetningarvilla

### ISSUE THREAD

**Issue by audunnb** [sveinn-steinarsson/is-trivia-questions#1]
https://github.com/sveinn-steinarsson/is-trivia-questions/blob/34903c90c367d4ebc71e76b7102f585a60ff417c/questions.csv#L404

Viðeigandi að það sé stafsetningarvilla í línu 404.
"6,Kvikmyndir og sjónvarpsefni,3,,Hver er seinna nafn Amélie í samnefndir kvikmynd,Poulain"

Ætti að vera: **Hvert** er seinna nafn... og **samnefndri**

**Comment by Kjarrval** [comment]
Lagað með commit 9014366cf8ad1f69ee1148e1ed73c5a4c511e01c .
